function [McNemarsWithCoordinatesSNP] = ...
    run_Exact_McNemars_filtered_SNP(DiploT_sort, PlinkMap, McNemarsCSV)
% 
% McNemarsWithCoordinatesSNP] =  ... 
% run_Exact_McNemars_filtered_SNP(DiploT_sort, PlinkMap, McNemarsCSV)
% 
% This script's inputs are a diplotype array, PlinkMap (mapping of SNP 
% to genome coordinates, and McNemarsCSV (the CSV file name) into which to 
% write the McNemars statistics at each SNP. Each SNP is represented by a 
% row in the CSV. Please note that orientation of the SNP in the output CSV 
% file is transposed from the diplotype array. The first few columns of the 
% CSV are occupied byt SNP ID, genome location, and other SNP metadata
% with the rest of the columns occupied by McNemars statistics and
% occupancy of the contingency table quadrants for the three cases
% considered, where for the allele in question (A,C,G, or T) there was 
% ExactlyOneAllelePresent, ExactlyOneorTwoAllelePresent, or 
% ExactlyTwoAllelePresent in Qb or Qc ... by definition, the allele is 
% present in the case but not control, and vice versa. 
% Perform analysis for both the high frequency and low frequency alleles 
% (these SNP are biallelic) at each SNP for a total of 2 x 3 = 6 
% different McNeamers tests at every SNP.


% convert PLINK MAP file into table

PlinkMapTable = readtable(PlinkMap,"FileType","text", "Delimiter","\t","ReadVariableNames",false);

numsnp = size(DiploT_sort);

tic


parfor i = 1:numsnp(2)
    
    % Determine high and low frequency alleles

    [AlleleHighFreq(i),AlleleLowFreq(i)] = GetSNPAlleleFreqs(DiploT_sort,i);
    
    [ExactOneHF_ChiSQR(i),ExactOneHF_ChiSQR_CC(i),ExactOneHF_p_Exact(i), ...
        ExactOneHF_p_Mid(i),ExactOneHF_a(i),ExactOneHF_b(i), ...
        ExactOneHF_c(i),ExactOneHF_d(i)] ...
        = McNemarsScoreExactIn(AlleleHighFreq(i),1, DiploT_sort,i);
    
    [ExactOneLF_ChiSQR(i),ExactOneLF_ChiSQR_CC(i),ExactOneLF_p_Exact(i), ...
        ExactOneLF_p_Mid(i), ExactOneLF_a(i),ExactOneLF_b(i), ...
        ExactOneLF_c(i),ExactOneLF_d(i)] ...
        = McNemarsScoreExactIn(AlleleLowFreq(i),1, DiploT_sort,i);
    
    [ExactOneOrTwoHF_ChiSQR(i),ExactOneOrTwoHF_ChiSQR_CC(i), ...
        ExactOneOrTwoHF_p_Exact(i), ExactOneOrTwoHF_p_Mid(i), ...
        ExactOneOrTwoHF_a(i), ...
        ExactOneOrTwoHF_b(i),ExactOneOrTwoHF_c(i),ExactOneOrTwoHF_d(i)] ...
        = McNemarsScoreExactIn(AlleleHighFreq(i),1.5, DiploT_sort,i);
    
    [ExactOneOrTwoLF_ChiSQR(i),ExactOneOrTwoLF_ChiSQR_CC(i),...
        ExactOneOrTwoLF_p_Exact(i),ExactOneOrTwoLF_p_Mid(i), ...
        ExactOneOrTwoLF_a(i),...
        ExactOneOrTwoLF_b(i),ExactOneOrTwoLF_c(i),ExactOneOrTwoLF_d(i)] ...
        = McNemarsScoreExactIn(AlleleLowFreq(i),1.5, DiploT_sort,i);
    
    [ExactTwoHF_ChiSQR(i),ExactTwoHF_ChiSQR_CC(i),...
        ExactTwoHF_p_Exact(i), ExactTwoHF_p_Mid(i), ...
        ExactTwoHF_a(i), ...
        ExactTwoHF_b(i),ExactTwoHF_c(i),ExactTwoHF_d(i)] ...
        = McNemarsScoreExactIn(AlleleHighFreq(i),2, DiploT_sort,i);
    
    [ExactTwoLF_ChiSQR(i),ExactTwoLF_ChiSQR_CC(i),...
        ExactTwoLF_p_Exact(i), ExactTwoLF_p_Mid(i), ...
        ExactTwoLF_a(i),...
        ExactTwoLF_b(i),ExactTwoLF_c(i),ExactTwoLF_d(i)] ...
        = McNemarsScoreExactIn(AlleleLowFreq(i),2, DiploT_sort,i);
    
end


toc


McNeamersTable = table(AlleleHighFreq', ExactOneHF_a',ExactOneHF_b', ...
    ExactOneHF_c',ExactOneHF_d',...
    ExactOneHF_b' + ExactOneHF_c', ...
    ExactOneHF_a' + ExactOneHF_b' + ExactOneHF_c' + ExactOneHF_d', ...
    (ExactOneHF_b' + ExactOneHF_c')./ ...
    (ExactOneHF_a' + ExactOneHF_b' + ExactOneHF_c' + ExactOneHF_d'), ...
    ExactOneHF_b' ./ ExactOneHF_c', ExactOneHF_ChiSQR', ...
    ExactOneHF_ChiSQR_CC', ExactOneHF_p_Exact', ...
    -1 * log10(ExactOneHF_p_Exact'), ...
    ExactOneHF_p_Mid',...
    -1 * log10(ExactOneHF_p_Mid'), ...
    ExactOneOrTwoHF_a',ExactOneOrTwoHF_b',ExactOneOrTwoHF_c', ...
    ExactOneOrTwoHF_d', ...
    ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c', ...
    ExactOneOrTwoHF_a' + ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c' + ExactOneOrTwoHF_d', ...
    (ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c')./ ...
    (ExactOneOrTwoHF_a' + ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c' + ExactOneOrTwoHF_d'), ...
    ExactOneOrTwoHF_b' ./ ExactOneOrTwoHF_c', ...
    ExactOneOrTwoHF_ChiSQR', ...
    ExactOneOrTwoHF_ChiSQR_CC',ExactOneOrTwoHF_p_Exact', ...
    -1 * log10(ExactOneOrTwoHF_p_Exact'), ...
    ExactOneOrTwoHF_p_Mid', ...
    -1 * log10(ExactOneOrTwoHF_p_Mid'), ...
    ExactTwoHF_a',ExactTwoHF_b',ExactTwoHF_c',ExactTwoHF_d',...
    ExactTwoHF_b' + ExactTwoHF_c', ...
    ExactTwoHF_a' + ExactTwoHF_b' + ExactTwoHF_c' + ExactTwoHF_d', ...
    (ExactTwoHF_b' + ExactTwoHF_c')./ ...
    (ExactTwoHF_a' + ExactTwoHF_b' + ExactTwoHF_c' + ExactTwoHF_d'), ...
    ExactTwoHF_b' ./ ExactTwoHF_c', ...
    ExactTwoHF_ChiSQR',ExactTwoHF_ChiSQR_CC',ExactTwoHF_p_Exact', ...
    -1 * log10(ExactTwoHF_p_Exact'), ...
    ExactTwoHF_p_Mid', ...
    -1 * log10(ExactTwoHF_p_Mid'), ...
    AlleleLowFreq', ExactOneLF_a',ExactOneLF_b',ExactOneLF_c',ExactOneLF_d',...
    ExactOneLF_b' + ExactOneLF_c', ...
    ExactOneLF_a' + ExactOneLF_b' + ExactOneLF_c' + ExactOneLF_d', ...
    (ExactOneLF_b' + ExactOneLF_c') ./ ...
    (ExactOneLF_a' + ExactOneLF_b' + ExactOneLF_c' + ExactOneLF_d'),...
    ExactOneLF_b' ./ ExactOneLF_c', ...
    ExactOneLF_ChiSQR',ExactOneLF_ChiSQR_CC',ExactOneLF_p_Exact', ...
    -1 * log10(ExactOneLF_p_Exact'), ...
    ExactOneLF_p_Mid', ...
    -1 * log10(ExactOneLF_p_Mid'), ...
    ExactOneOrTwoLF_a',ExactOneOrTwoLF_b',ExactOneOrTwoLF_c', ...
    ExactOneOrTwoLF_d', ...
    ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c', ...
    ExactOneOrTwoLF_a' + ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c' + ExactOneOrTwoLF_d', ...
    (ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c')./ ...
    (ExactOneOrTwoLF_a' + ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c' + ExactOneOrTwoLF_d'), ...
    ExactOneOrTwoLF_b' ./ ExactOneOrTwoLF_c', ...
    ExactOneOrTwoLF_ChiSQR', ...
    ExactOneOrTwoLF_ChiSQR_CC',ExactOneOrTwoLF_p_Exact', ...
    -1 * log10(ExactOneOrTwoLF_p_Exact'), ...
    ExactOneOrTwoLF_p_Mid', ...
    -1 * log10(ExactOneOrTwoLF_p_Mid'), ...
    ExactTwoLF_a',ExactTwoLF_b',ExactTwoLF_c',ExactTwoLF_d',...
    ExactTwoLF_b' + ExactTwoLF_c', ...
    ExactTwoLF_a' + ExactTwoLF_b' + ExactTwoLF_c' + ExactTwoLF_d', ...
    (ExactTwoLF_b' + ExactTwoLF_c')./ ...
    (ExactTwoLF_a' + ExactTwoLF_b' + ExactTwoLF_c' + ExactTwoLF_d'), ...
    ExactTwoLF_b' ./ ExactTwoLF_c', ...
    ExactTwoLF_ChiSQR',ExactTwoLF_ChiSQR_CC',ExactTwoLF_p_Exact', ...
    -1 * log10(ExactTwoLF_p_Exact'), ...
    ExactTwoLF_p_Mid', ...
    -1 * log10(ExactTwoLF_p_Mid'), ...
    'VariableNames', ...
    {'HiFreqAllele','ExactOneHF_a','ExactOneHF_b', ...
    'ExactOneHF_c', 'ExactOneHF_d', ...
    'ExactOneHF_bPc', 'ExactOneHF_aPbPcPd', 'ExactOneHF_bPC_D_aPbPcPd', ...
    'ExactOneHF_bDc', ...
    'ExactOneHF_ChiSquared','ExactOneHF_ChiSquared_CC', ...
    'ExactOneHF_p_exact', ...
    'neg_log10_ExactOneHF_p_exact', ...
    'ExactOneHF_p_mid',...
    'neg_log10_ExactOneHF_p_mid', ...
    'ExactOneOrTwoHF_a','ExactOneOrTwoHF_b','ExactOneOrTwoHF_c',...
    'ExactOneOrTwoHF_d', ...
    'ExactOneOrTwoHF_bPc', 'ExactOneOrTwoHF_aPbPcPd', ...
    'ExactOneOrTwoHF_bPC_D_aPbPcPd', 'ExactOneOrTwoHF_bDc', ...
    'ExactOneOrTwoHF_ChiSquared', ...
    'ExactOneOrTwoHF_ChiSquared_CC', 'ExactOneOrTwoHF_p_exact', ...
    'neg_log10_ExactOneOrTwoHF_p_exact', ...
    'ExactOneOrTwoHF_p_mid', ...
    'neg_log10_ExactOneOrTwoHF_p_mid', ...
    'ExactTwoHF_a','ExactTwoHF_b','ExactTwoHF_c','ExactTwoHF_d', ...
    'ExactTwoHF_bPc', 'ExactTwoHF_aPbPcPd', ...
    'ExactTwoHF_bPC_D_aPbPcPd', 'ExactTwoHF_bDc', ...
    'ExactTwoHF_ChiSquared','ExactTwoHF_ChiSquared_CC','ExactTwoHF_p_exact', ...
    'neg_log10_ExactTwoHF_p_exact', ...
    'ExactTwoHF_p_mid', ...
    'neg_log10_ExactTwoHF_p_mid', ...
    'LowFreqAllele','ExactOneLF_a','ExactOneLF_b','ExactOneLF_c',...
    'ExactOneLF_d', ...
    'ExactOneLF_bPc', 'ExactOneLF_aPbPcPd', ...
    'ExactOneLF_bPC_D_aPbPcPd', 'ExactOneLF_bDc', ...
    'ExactOneLF_ChiSquared','ExactOneLF_ChiSquared_CC', ...
    'ExactOneLF_p_exact', ...
    'neg_log10_ExactOneLF_p_exact', ...
    'ExactOneLF_p_mid', ...
    'neg_log10_ExactOneLF_p_mid', ...
    'ExactOneOrTwoLF_a','ExactOneOrTwoLF_b','ExactOneOrTwoLF_c',...
    'ExactOneOrTwoLF_d', ...
    'ExactOneOrTwoLF_bPc', 'ExactOneOrTwoLF_aPbPcPd', ...
    'ExactOneOrTwoLF_bPC_D_aPbPcPd', 'ExactOneOrTwoLF_bDc', ...
    'ExactOneOrTwoLF_ChiSquared', ...
    'ExactOneOrTwoLF_ChiSquared_CC', 'ExactOneOrTwoLF_p_exact', ...
    'neg_log10_ExactOneOrTwoLF_p_exact', ...
    'ExactOneOrTwoLF_p_mid', ...
    'neg_log10_ExactOneOrTwoLF_p_mid', ...
    'ExactTwoLF_a','ExactTwoLF_b','ExactTwoLF_c','ExactTwoLF_d', ...
    'ExactTwoLF_bPc', 'ExactTwoLF_aPbPcPd', ...
    'ExactTwoLF_bPC_D_aPbPcPd', 'ExactTwoLF_bDc', ...
    'ExactTwoLF_ChiSquared','ExactTwoLF_ChiSquared_CC', ...
    'ExactTwoLF_p_exact', ...
    'neg_log10_ExactTwoLF_p_exact', ...
    'ExactTwoLF_p_mid',...
    'neg_log10_ExactTwoLF_p_mid'});

McNemarsWithCoordinatesSNP= horzcat(PlinkMapTable,McNeamersTable);

writetable(McNemarsWithCoordinatesSNP,McNemarsCSV);