
function [McNemarsWithCoordinatesSNP] = ...
    run_Exact_McNemars_filtered_SNP(DiploT_sort, PlinkMap, McNemarsCSV)

% Assume starting with unsorted diploT array, need to sort using metadata
% in Paired_metadata_array

% Whole Array Operations
% First, read in paired_metadata array as Pairedmetadataarray

% [DiploT_sort, Paired_metadata_sort] = SortDiploT(diploT_array,Pairedmetadataarray);

% Command inside a loop to process every SNP in diplotype array of SNP


% convert MAP file into table

PlinkMapTable = readtable(PlinkMap,"FileType","text", "Delimiter","\t","ReadVariableNames",false);

numsnp = size(DiploT_sort);

tic

parfor i = 1:numsnp(2)
    
%     filterbad = cell2table(tabulate(diploT_array(:,i))); % find no calls
%     filterbad.Var1 = string(filterbad.Var1);
%     nocallsIndex = find(filterbad.Var1 == "0");
%     nobadcall = isempty(nocallsIndex); % no bad call means nobadcall = 1
%     
%     if nobadcall ~= 1     % look for no call in filter bad        
%         nocallfreq = filterbad.Var3(nocallsIndex);      
%         if nocallfreq > 10
%             continue % skip this SNP in loop, go to next iteration
%         end     
%     end
%       
    
    [AlleleHighFreq(i),AlleleLowFreq(i)] = GetSNPAlleleFreqs(DiploT_sort,i);
    
    % [singleA_ChiSQR(i),singleA_ChiSQR_CC(i),singleA_p_Exact(i),singleA_a(i),singleA_b(i),...
    %     singleA_c(i),singleA_d(i)] = McNemarsScoreSNPSingleA(AlleleHighFreq(i), DiploT_sort,i);
    
    [ExactOneHF_ChiSQR(i),ExactOneHF_ChiSQR_CC(i),ExactOneHF_p_Exact(i),ExactOneHF_a(i), ...
        ExactOneHF_b(i), ExactOneHF_c(i),ExactOneHF_d(i)] ...
        = McNemarsScoreExactIn(AlleleHighFreq(i),1, DiploT_sort,i);
    
    [ExactOneLF_ChiSQR(i),ExactOneLF_ChiSQR_CC(i),ExactOneLF_p_Exact(i),ExactOneLF_a(i), ...
        ExactOneLF_b(i), ExactOneLF_c(i),ExactOneLF_d(i)] ...
        = McNemarsScoreExactIn(AlleleLowFreq(i),1, DiploT_sort,i);
    
    [ExactOneOrTwoHF_ChiSQR(i),ExactOneOrTwoHF_ChiSQR_CC(i),ExactOneOrTwoHF_p_Exact(i),...
        ExactOneOrTwoHF_a(i),ExactOneOrTwoHF_b(i),ExactOneOrTwoHF_c(i),ExactOneOrTwoHF_d(i)] ...
        = McNemarsScoreExactIn(AlleleHighFreq(i),1.5, DiploT_sort,i);
    
    [ExactOneOrTwoLF_ChiSQR(i),ExactOneOrTwoLF_ChiSQR_CC(i),ExactOneOrTwoLF_p_Exact(i),...
        ExactOneOrTwoLF_a(i),ExactOneOrTwoLF_b(i),ExactOneOrTwoLF_c(i),ExactOneOrTwoLF_d(i)] ...
        = McNemarsScoreExactIn(AlleleLowFreq(i),1.5, DiploT_sort,i); 
    
    [ExactTwoHF_ChiSQR(i),ExactTwoHF_ChiSQR_CC(i),ExactTwoHF_p_Exact(i),ExactTwoHF_a(i),...
        ExactTwoHF_b(i),ExactTwoHF_c(i),ExactTwoHF_d(i)] ...
        = McNemarsScoreExactIn(AlleleHighFreq(i),2, DiploT_sort,i);
    
    [ExactTwoLF_ChiSQR(i),ExactTwoLF_ChiSQR_CC(i),ExactTwoLF_p_Exact(i),ExactTwoLF_a(i),...
        ExactTwoLF_b(i),ExactTwoLF_c(i),ExactTwoLF_d(i)] ...
        = McNemarsScoreExactIn(AlleleLowFreq(i),2, DiploT_sort,i);
    
    %[doubleA_ChiSQR(i),doubleA_ChiSQR_CC(i),doubleA_p_Exact(i),doubleA_a(i),doubleA_b(i),...
    %  doubleA_c(i),doubleA_d(i)] = McNemarsScoreSNPDoubleA(AlleleHighFreq(i), DiploT_sort,i);  
    
end


toc


McNeamersTable = table(AlleleHighFreq', ExactOneHF_a',ExactOneHF_b', ...
    ExactOneHF_c',ExactOneHF_d',...
    ExactOneHF_b' + ExactOneHF_c', ...
    ExactOneHF_a' + ExactOneHF_b' + ExactOneHF_c' + ExactOneHF_d', ...
    (ExactOneHF_b' + ExactOneHF_c')./ ...
    (ExactOneHF_a' + ExactOneHF_b' + ExactOneHF_c' + ExactOneHF_d'), ...
    ExactOneHF_b' ./ ExactOneHF_c', ExactOneHF_ChiSQR', ... 
    ExactOneHF_ChiSQR_CC', ExactOneHF_p_Exact', ...
    -1 * log10(ExactOneHF_p_Exact'), ...
    ExactOneOrTwoHF_a',ExactOneOrTwoHF_b',ExactOneOrTwoHF_c', ...
    ExactOneOrTwoHF_d', ... 
    ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c', ...
    ExactOneOrTwoHF_a' + ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c' + ExactOneOrTwoHF_d', ...
    (ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c')./ ...
    (ExactOneOrTwoHF_a' + ExactOneOrTwoHF_b' + ExactOneOrTwoHF_c' + ExactOneOrTwoHF_d'), ...
    ExactOneOrTwoHF_b' ./ ExactOneOrTwoHF_c', ...
    ExactOneOrTwoHF_ChiSQR', ...
    ExactOneOrTwoHF_ChiSQR_CC',ExactOneOrTwoHF_p_Exact', ...
    -1 * log10(ExactOneOrTwoHF_p_Exact'), ...
    ExactTwoHF_a',ExactTwoHF_b',ExactTwoHF_c',ExactTwoHF_d',...
    ExactTwoHF_b' + ExactTwoHF_c', ...
    ExactTwoHF_a' + ExactTwoHF_b' + ExactTwoHF_c' + ExactTwoHF_d', ...
    (ExactTwoHF_b' + ExactTwoHF_c')./ ...
    (ExactTwoHF_a' + ExactTwoHF_b' + ExactTwoHF_c' + ExactTwoHF_d'), ...
    ExactTwoHF_b' ./ ExactTwoHF_c', ...
    ExactTwoHF_ChiSQR',ExactTwoHF_ChiSQR_CC',ExactTwoHF_p_Exact', ...
     -1 * log10(ExactTwoHF_p_Exact'), ...
    AlleleLowFreq', ExactOneLF_a',ExactOneLF_b',ExactOneLF_c',ExactOneLF_d',...
    ExactOneLF_b' + ExactOneLF_c', ...
    ExactOneLF_a' + ExactOneLF_b' + ExactOneLF_c' + ExactOneLF_d', ...
    (ExactOneLF_b' + ExactOneLF_c') ./ ...
    (ExactOneLF_a' + ExactOneLF_b' + ExactOneLF_c' + ExactOneLF_d'),...
    ExactOneLF_b' ./ ExactOneLF_c', ...    
    ExactOneLF_ChiSQR',ExactOneLF_ChiSQR_CC',ExactOneLF_p_Exact', ...
    -1 * log10(ExactOneLF_p_Exact'), ...    
    ExactOneOrTwoLF_a',ExactOneOrTwoLF_b',ExactOneOrTwoLF_c', ...
    ExactOneOrTwoLF_d', ...
    ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c', ...
    ExactOneOrTwoLF_a' + ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c' + ExactOneOrTwoLF_d', ...
    (ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c')./ ...
    (ExactOneOrTwoLF_a' + ExactOneOrTwoLF_b' + ExactOneOrTwoLF_c' + ExactOneOrTwoLF_d'), ...
    ExactOneOrTwoLF_b' ./ ExactOneOrTwoLF_c', ...
    ExactOneOrTwoLF_ChiSQR', ...
    ExactOneOrTwoLF_ChiSQR_CC',ExactOneOrTwoLF_p_Exact', ...
    -1 * log10(ExactOneOrTwoLF_p_Exact'), ...
    ExactTwoLF_a',ExactTwoLF_b',ExactTwoLF_c',ExactTwoLF_d',...
    ExactTwoLF_b' + ExactTwoLF_c', ...
    ExactTwoLF_a' + ExactTwoLF_b' + ExactTwoLF_c' + ExactTwoLF_d', ...
    (ExactTwoLF_b' + ExactTwoLF_c')./ ...
    (ExactTwoLF_a' + ExactTwoLF_b' + ExactTwoLF_c' + ExactTwoLF_d'), ...
    ExactTwoLF_b' ./ ExactTwoLF_c', ...
    ExactTwoLF_ChiSQR',ExactTwoLF_ChiSQR_CC',ExactTwoLF_p_Exact', ...
    -1 * log10(ExactTwoLF_p_Exact'), ...   
    'VariableNames',{'HiFreqAllele','ExactOneHF_a','ExactOneHF_b', ...
    'ExactOneHF_c', 'ExactOneHF_d', ...
    'ExactOneHF_b+c', 'ExactOneHF_a+b+c+d', 'ExactOneHF_(b+c)/(a+b+c+d)', ...
    'ExactOneHF_b/c', ...
    'ExactOneHF_ChiSquared','ExactOneHF_ChiSquared_CC', ...
    'ExactOneHF_p_exact', ...
    '-log10(ExactOneHF_p)', ...
    'ExactOneOrTwoHF_a','ExactOneOrTwoHF_b','ExactOneOrTwoHF_c',...
    'ExactOneOrTwoHF_d', ...
     'ExactOneOrTwoHF_b+c', 'ExactOneOrTwoHF_a+b+c+d', ...
     'ExactOneOrTwoHF_(b+c)/(a+b+c+d)', 'ExactOneOrTwoHF_b/c', ...
    'ExactOneOrTwoHF_ChiSquared', ...
    'ExactOneOrTwoHF_ChiSquared_CC', 'ExactOneOrTwoHF_p_exact', ...
     '-log10(ExactOneorTwoHF_p)', ...
    'ExactTwoHF_a','ExactTwoHF_b','ExactTwoHF_c','ExactTwoHF_d', ...
    'ExactTwoHF_b+c', 'ExactTwoHF_a+b+c+d', ...
    'ExactTwoHF_(b+c)/(a+b+c+d)', 'ExactTwoHF_b/c', ...
    'ExactTwoHF_ChiSquared','ExactTwoHF_ChiSquared_CC','ExactTwoHF_p_exact', ...
     '-log10(ExactTwoHF_p)', ...
    'LowFreqAllele','ExactOneLF_a','ExactOneLF_b','ExactOneLF_c',...
    'ExactOneLF_d', ...
    'ExactOneLF_b+c', 'ExactOneLF_a+b+c+d', ...
    'ExactOneLF_(b+c)/(a+b+c+d)', 'ExactOneLF_b/c', ...
    'ExactOneLF_ChiSquared','ExactOneLF_ChiSquared_CC', ...
    'ExactOneLF_p_exact', ...
     '-log10(ExactOneLF_p)', ...
    'ExactOneOrTwoLF_a','ExactOneOrTwoLF_b','ExactOneOrTwoLF_c',...
    'ExactOneOrTwoLF_d', ...
    'ExactOneOrTwoLF_b+c', 'ExactOneOrTwoLF_a+b+c+d', ...
    'ExactOneOrTwoLF_(b+c)/(a+b+c+d)', 'ExactOneOrTwoLF_b/c', ...
    'ExactOneOrTwoLF_ChiSquared', ...
    'ExactOneOrTwoLF_ChiSquared_CC', 'ExactOneOrTwoLF_p_exact', ...
     '-log10(ExactOneorTwoLF_p)', ...
    'ExactTwoLF_a','ExactTwoLF_b','ExactTwoLF_c','ExactTwoLF_d', ...
    'ExactTwoLF_b+c', 'ExactTwoLF_a+b+c+d', ... 
    'ExactTwoLF_(b+c)/(a+b+c+d)', 'ExactTwoLF_b/c', ...
    'ExactTwoLF_ChiSquared','ExactTwoLF_ChiSquared_CC', ...
    'ExactTwoLF_p_exact', ...
    '-log10(ExactTwoLF_p)'});

McNemarsWithCoordinatesSNP= horzcat(PlinkMapTable,McNeamersTable);

writetable(McNemarsWithCoordinatesSNP,McNemarsCSV);